config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # get 'login/new'
mount Sidekiq::Web.new => '/sidekiq'
  # get 'login/create'
  # get 'signups/index'
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :signups
  resources :logins
  # Defines the root path route ("/")
  # root "articles#index"
  delete'logout' => "signups#destroy"
  #mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/signup.rb
class Signup < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        @_current_user = @_current_user || Signup.find(session[:current_user_id]) if session[:current_user_id]
    end
    helper_method :current_user
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def show 
      @signup=Signup.all
  end

  def create 
        signup = Signup.find_by(email: params[:email])
        if signup && signup.authenticate(params[:password])
          session[:signup_id] = signup.id
          redirect_to signups_path
        else
          #flash.now.alert = "Email or password is invalid"
          render "new"
        end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  http_basic_authenticate_with name: "humbaba", password: "5baa61e4"
  def index
    @signup = Signup.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @signup }
      format.json { render json: @signup }
    end
  end
  
  def show 
    @signup=Signup.find(params[:id])
  end
  
  def new
    @signup=Signup.new 
  end

  def create 
    # debugger 
    @signup=Signup.new(signup_params)
    if @signup.save 
      # SignupMailer.welcome_email.deliver
      #SignupMailer.with(signup: @signup).welcome_email.deliver_now
      SignupJob.perform_now(@signup)

      redirect_to new_login_path
    else
      render "new"
    end
  end
  
  def destroy
    # Remove the user id from the session
    session.delete(:current_user_id)
    # Clear the memoized current user
    @_current_user = nil
    redirect_to new_login_path
  end

  private 
    def signup_params 
      params.require(:signup).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<h1>Login</h1>
<%= form_with url: logins_path do %>
    <%= label_tag "Username" %>
    <%= text_field_tag :email%>
    <%= label_tag "Password" %>
    <%= password_field_tag :password%>
    <%= submit_tag "Log In"%>
<% end %>

app/views/logins/show.html.erb
<p>Show page login</p>
<h1>Welcome to the home page</h1>

app/views/signups/index.html.erb
<h1>Signups#index</h1>
<ul>
  <% @signup.each do |signup| %>
    <li>
      <%= signup.email %>
      <%= signup.password%>
    </li>
  <% end %>
</ul>

<%= link_to "New Signup", new_signup_path %>
<%= link_to "logout", logout_path , data: {turbo_method: :delete , turbo_confirm:"are you sure?"}%>

app/views/signups/new.html.erb
<h1>SignUp Page</h1>
<%= form_with model: @signup do |form| %>
  <div>
      <%= form.label :email, "Email"%>
      <%=form.text_field :email %>
    </div>
    <div>
      <%= form.label :password, "Password" %>
      <%= form.text_field :password%>
    </div>
    <!--<div>
      <%= form.label :password_confirmation , "Password_confirmation" %>
      <%=form.text_field :password_confirmation%>
    </div>-->
    <div>
    <%= form.submit "submit" %>
    </div>
    <div>
    <% end %>
    </div>

app/views/signups/show.html.erb
<h1>Show Page</h1>
<%= @signup.email%>
<%= @signup.password%>